name: Deploy to Firebase Hosting feature
on:
  push:
    branches:
      - 'feature/*'
      - 'fix/*'
  pull_request:
    branches:
      - 'feature/*'
      - 'fix/*'

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment: .env
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch master
        run: git fetch --no-tags --prune --depth=1 origin master

      - name: Install dependencies
        run: npm ci

      - name: Run affected tests
        run: npx nx affected -t test --base=origin/master --head=HEAD --skip-nx-cache

      - name: Build Web Frontend
        run: npx nx build web-frontend
        env:
          VITE_FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}
          VITE_FIREBASE_APP_ID: ${{ secrets.VITE_FIREBASE_APP_ID }}
          VITE_FIREBASE_MEASUREMENT_ID: ${{ secrets.VITE_FIREBASE_MEASUREMENT_ID }}
          VITE_FIREBASE_PROJECT_ID: ${{ vars.VITE_FIREBASE_PROJECT_ID }}
          VITE_FIREBASE_STORAGE_BUCKET: ${{ vars.VITE_FIREBASE_STORAGE_BUCKET }}
          VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ vars.VITE_FIREBASE_MESSAGING_SENDER_ID }}

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_DIANAFITLAB_10ECA }}
          projectId: dianafitlab-10eca
